global:
  scrape_interval: 15s  # Collecte toutes les 15 secondes
  evaluation_interval: 15s

scrape_configs:
  # ===============================
  # AUTH SERVICE - Port 8082
  # ===============================
  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'auth-service'
          service: 'authentication'

  # ===============================
  # DOCTOR ACTIVATION SERVICE - Port 8083
  # ===============================
  - job_name: 'doctor-activation-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          application: 'doctor-activation-service'
          service: 'doctor-management'

  # ===============================
  # USER SERVICE - Port 8085
  # ===============================
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8085']
        labels:
          application: 'user-service'
          service: 'user-management'

  # ===============================
  # EUREKA SERVER - Port 8761
  # ===============================
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8761']
        labels:
          application: 'eureka-server'
          service: 'service-discovery'